# kubernetes/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mpi-worker
spec:
  serviceName: mpi-service
  replicas: 4
  selector:
    matchLabels:
      app: mpi-worker
  template:
    metadata:
      labels:
        app: mpi-worker
    spec:
      containers:
      - name: mpi-worker
        image: ynshung/mpi-sort:latest
        command: ["/bin/bash", "-c"]
        volumeMounts:
        - name: ssh-keys
          mountPath: /etc/ssh-keys
          readOnly: true
        - name: ssh-config
          mountPath: /etc/ssh-config
          readOnly: true
        args:
        - |
          apt-get update && apt-get install -y openssh-server
          mkdir -p /root/.ssh
          cp /etc/ssh-keys/ssh-privatekey /root/.ssh/id_rsa
          cp /etc/ssh-keys/ssh-publickey /root/.ssh/id_rsa.pub
          cp /etc/ssh-keys/authorized_keys /root/.ssh/authorized_keys
          chmod 600 /root/.ssh/id_rsa
          chmod 644 /root/.ssh/id_rsa.pub
          chmod 644 /root/.ssh/authorized_keys
          rm /etc/ssh/sshd_config
          cp /etc/ssh-config/sshd_config /etc/ssh
          service ssh restart  # Use restart instead of just start
          sleep infinity
        ports:
        - containerPort: 22
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
          defaultMode: 0600
      - name: ssh-config
        configMap:
          name: ssh-config